/**
 * Seed: 30 realistic rooms with location metadata and images.
 */

// Only 100% verified working Unsplash photo IDs for rooms/apartments
const PHOTO_IDS = [
  '1522708323590-d24dbb6b0267', '1505693416388-ac5ce068fe85', '1560448204-e02f11c3d0e2',
  '1493809842364-78817add7ffb', '1484154218962-a197022b5858', '1513694203232-719a280e022f',
  '1560185893-a55cbc8c57e8',   '1560448075-bb485b067938',   '1560448204-603b3fc33ddc',
  '1560185007-cde436f6a4d0',   '1560440021-33f9b867899d',   '1560185127-6ed189bf02f4',
  '1560184897-ae75f418493e',   '1560448205-4d9b3e6bb6db',   '1499951360447-b19be8fe80f5',
  '1522771739844-6a9f6d5f14af', '1497366216548-37526070297c', '1463620910506-d0458143143e',
  '1505691938895-1758d7feb511', '1505873242700-f289a29e1e0f', '1507089947368-19c1da9775ae',
  '1502005229762-cf1b2da7c5d6', '1464146072230-91cabc968266'
];

function imageUrl(roomIndex, imageIndex) {
  // Use sequential unique images from the large pool
  // Added a pseudo-random multiplier to ensure different combinations for each room
  const offset = ((roomIndex * 7) + imageIndex * 3) % PHOTO_IDS.length;
  const photoId = PHOTO_IDS[offset];
  return `https://images.unsplash.com/photo-${photoId}?auto=format&fit=crop&w=1200&q=80`;
}

const rooms = [
  {
    title: 'Studio ban công gần Landmark 81',
    room_type: 'Căn hộ',
    detailed_address: '208 Nguyễn Hữu Cảnh',
    ward_name: 'Phường 22',
    district_name: 'Bình Thạnh',
    province_name: 'Hồ Chí Minh',
    formatted_address: '208 Nguyễn Hữu Cảnh, Phường 22, Bình Thạnh, Hồ Chí Minh, Việt Nam',
    latitude: 10.795396,
    longitude: 106.721803,
    max_capacity: 2,
    monthly_rent: 7200000,
    deposit_amount: 7200000,
    electricity_cost: 4200,
    water_cost: 25000,
    internet_cost: 120000,
    service_fee: 150000,
    average_rating: 4.8,
    room_description: 'Studio sang trọng, có ban công rộng rãi, bếp riêng tư, trang bị đầy đủ máy lạnh, máy giặt chung và bảo vệ an ninh 24/7.',
  },
  {
    title: 'Phòng gác lửng gần Đại học Bách Khoa',
    room_type: 'Phòng trọ',
    detailed_address: '268 Lý Thường Kiệt',
    ward_name: 'Phường 14',
    district_name: 'Quận 10',
    province_name: 'Hồ Chí Minh',
    formatted_address: '268 Lý Thường Kiệt, Phường 14, Quận 10, Hồ Chí Minh, Việt Nam',
    latitude: 10.772132,
    longitude: 106.657823,
    max_capacity: 2,
    monthly_rent: 3800000,
    deposit_amount: 3800000,
    electricity_cost: 4000,
    water_cost: 22000,
    internet_cost: 80000,
    service_fee: 60000,
    average_rating: 4.4,
    room_description: 'Phòng có gác lửng thoáng mát, cửa sổ lớn đón ánh sáng tự nhiên, vị trí gần trường đại học, giờ giấc tự do và có chỗ để xe an toàn trong nhà.',
  },
  {
    title: 'Căn hộ mini full nội thất Nguyễn Trãi',
    room_type: 'Căn hộ',
    detailed_address: '214 Nguyễn Trãi',
    ward_name: 'Phường Nguyễn Cư Trinh',
    district_name: 'Quận 1',
    province_name: 'Hồ Chí Minh',
    formatted_address: '214 Nguyễn Trãi, Phường Nguyễn Cư Trinh, Quận 1, Hồ Chí Minh, Việt Nam',
    latitude: 10.764219,
    longitude: 106.687748,
    max_capacity: 3,
    monthly_rent: 8600000,
    deposit_amount: 8600000,
    electricity_cost: 4300,
    water_cost: 25000,
    internet_cost: 150000,
    service_fee: 180000,
    average_rating: 4.7,
    room_description: 'Căn hộ mini đầy đủ nội thất cao cấp, khu vực bếp tách biệt sạch sẽ, vị trí sầm uất gần phố đi bộ Bùi Viện và trung tâm Quận 1.',
  },
  {
    title: 'Phòng trọ mới xây gần Etown Cộng Hòa',
    room_type: 'Phòng trọ',
    detailed_address: '364 Cộng Hòa',
    ward_name: 'Phường 13',
    district_name: 'Tân Bình',
    province_name: 'Hồ Chí Minh',
    formatted_address: '364 Cộng Hòa, Phường 13, Tân Bình, Hồ Chí Minh, Việt Nam',
    latitude: 10.801003,
    longitude: 106.639143,
    max_capacity: 2,
    monthly_rent: 4500000,
    deposit_amount: 4500000,
    electricity_cost: 4000,
    water_cost: 23000,
    internet_cost: 100000,
    service_fee: 80000,
    average_rating: 4.5,
    room_description: 'Phòng mới tinh 100%, có nhà vệ sinh riêng tiện lợi, trang bị thang máy hiện đại, vị trí rất gần toà nhà Etown và sân bay Tân Sơn Nhất.',
  },
  {
    title: 'Studio Yên Thế khu vực sân bay',
    room_type: 'Căn hộ',
    detailed_address: '47 Yên Thế',
    ward_name: 'Phường 2',
    district_name: 'Tân Bình',
    province_name: 'Hồ Chí Minh',
    formatted_address: '47 Yên Thế, Phường 2, Tân Bình, Hồ Chí Minh, Việt Nam',
    latitude: 10.813658,
    longitude: 106.665463,
    max_capacity: 2,
    monthly_rent: 6200000,
    deposit_amount: 6200000,
    electricity_cost: 4200,
    water_cost: 25000,
    internet_cost: 120000,
    service_fee: 120000,
    average_rating: 4.6,
    room_description: 'Căn hộ studio ngay khu vực sân bay, thiết kế nội thất thông minh và gọn gàng, sở hữu cửa sổ lớn, thuộc khu vực dân cư yên tĩnh, an ninh.',
  },
  {
    title: 'Phòng ban công lớn đường Phan Xích Long',
    room_type: 'Phòng trọ',
    detailed_address: '128 Phan Xích Long',
    ward_name: 'Phường 7',
    district_name: 'Phú Nhuận',
    province_name: 'Hồ Chí Minh',
    formatted_address: '128 Phan Xích Long, Phường 7, Phú Nhuận, Hồ Chí Minh, Việt Nam',
    latitude: 10.799985,
    longitude: 106.684606,
    max_capacity: 2,
    monthly_rent: 5200000,
    deposit_amount: 5200000,
    electricity_cost: 4100,
    water_cost: 24000,
    internet_cost: 100000,
    service_fee: 90000,
    average_rating: 4.5,
    room_description: 'Phòng có cửa sổ cực lớn đón nắng sớm, xung quanh là khu phố ẩm thực nhiều tiện ích, trang bị sẵn máy lạnh tiết kiệm điện và tủ lạnh cá nhân.',
  },
  {
    title: 'Căn hộ dịch vụ cao cấp Thảo Điền',
    room_type: 'Căn hộ',
    detailed_address: '21 Quốc Hương',
    ward_name: 'Thảo Điền',
    district_name: 'Thành phố Thủ Đức',
    province_name: 'Hồ Chí Minh',
    formatted_address: '21 Quốc Hương, Thảo Điền, Thành phố Thủ Đức, Hồ Chí Minh, Việt Nam',
    latitude: 10.806878,
    longitude: 106.732432,
    max_capacity: 2,
    monthly_rent: 9800000,
    deposit_amount: 9800000,
    electricity_cost: 4500,
    water_cost: 28000,
    internet_cost: 180000,
    service_fee: 250000,
    average_rating: 4.9,
    room_description: 'Căn hộ dịch vụ đẳng cấp dành cho chuyên gia, nội thất thiết kế theo phong cách hiện đại, sát tuyến metro Thảo Điền, có bao gồm dịch vụ dọn phòng hàng tuần.',
  },
  {
    title: 'Phòng giá sinh viên gần ĐH Tôn Đức Thắng',
    room_type: 'Phòng trọ',
    detailed_address: '19 Nguyễn Hữu Thọ',
    ward_name: 'Tân Phong',
    district_name: 'Quận 7',
    province_name: 'Hồ Chí Minh',
    formatted_address: '19 Nguyễn Hữu Thọ, Tân Phong, Quận 7, Hồ Chí Minh, Việt Nam',
    latitude: 10.729355,
    longitude: 106.700887,
    max_capacity: 2,
    monthly_rent: 4100000,
    deposit_amount: 4100000,
    electricity_cost: 3900,
    water_cost: 22000,
    internet_cost: 80000,
    service_fee: 70000,
    average_rating: 4.3,
    room_description: 'Phòng ốc sạch sẽ, mức giá cực kỳ phải chăng, cực gần Lotte Mart Quận 7 và Đại học Tôn Đức Thắng, sở hữu bãi đậu xe rộng rãi.',
  },
  {
    title: 'Studio Mỹ Đình ngõ rộng',
    room_type: 'Căn hộ',
    detailed_address: '35 Lê Đức Thọ',
    ward_name: 'Mỹ Đình 2',
    district_name: 'Nam Từ Liêm',
    province_name: 'Hà Nội',
    formatted_address: '35 Lê Đức Thọ, Mỹ Đình 2, Nam Từ Liêm, Hà Nội, Việt Nam',
    latitude: 21.030401,
    longitude: 105.778334,
    max_capacity: 2,
    monthly_rent: 5600000,
    deposit_amount: 5600000,
    electricity_cost: 4000,
    water_cost: 25000,
    internet_cost: 120000,
    service_fee: 100000,
    average_rating: 4.4,
    room_description: 'Căn hộ studio vị trí gần bến xe Mỹ Đình, trang bị nội thất cơ bản đầy đủ, tòa nhà có thang máy an toàn, ra vào bằng khóa vân tay bảo mật.',
  },
  {
    title: 'Phòng ban công đẹp gần Hồ Gươm',
    room_type: 'Phòng trọ',
    detailed_address: '12 Hàng Bài',
    ward_name: 'Tràng Tiền',
    district_name: 'Hoàn Kiếm',
    province_name: 'Hà Nội',
    formatted_address: '12 Hàng Bài, Tràng Tiền, Hoàn Kiếm, Hà Nội, Việt Nam',
    latitude: 21.023883,
    longitude: 105.852196,
    max_capacity: 2,
    monthly_rent: 6800000,
    deposit_amount: 6800000,
    electricity_cost: 4200,
    water_cost: 26000,
    internet_cost: 120000,
    service_fee: 160000,
    average_rating: 4.7,
    room_description: 'Phòng trọ vị trí đắc địa ngay trung tâm Hoàn Kiếm, chỉ mất 3 phút đi bộ ra Hồ Gươm, vô cùng phù hợp cho người đi làm văn phòng.',
  },
  {
    title: 'Căn hộ 1 phòng ngủ Cầu Giấy',
    room_type: 'Căn hộ',
    detailed_address: '88 Trần Thái Tông',
    ward_name: 'Dịch Vọng Hậu',
    district_name: 'Cầu Giấy',
    province_name: 'Hà Nội',
    formatted_address: '88 Trần Thái Tông, Dịch Vọng Hậu, Cầu Giấy, Hà Nội, Việt Nam',
    latitude: 21.035639,
    longitude: 105.789401,
    max_capacity: 3,
    monthly_rent: 7800000,
    deposit_amount: 7800000,
    electricity_cost: 4200,
    water_cost: 26000,
    internet_cost: 150000,
    service_fee: 180000,
    average_rating: 4.6,
    room_description: 'Căn hộ chung cư mini không gian riêng biệt, khu vực phòng ngủ tách rời hoàn toàn phòng khách, nằm ngay khu tập trung nhiều tòa văn phòng Cầu Giấy.',
  },
  {
    title: 'Phòng khép kín đầy đủ tiện nghi gần Bạch Mai',
    room_type: 'Phòng trọ',
    detailed_address: '78 Giải Phóng',
    ward_name: 'Phương Mai',
    district_name: 'Đống Đa',
    province_name: 'Hà Nội',
    formatted_address: '78 Giải Phóng, Phương Mai, Đống Đa, Hà Nội, Việt Nam',
    latitude: 21.001084,
    longitude: 105.841165,
    max_capacity: 2,
    monthly_rent: 4300000,
    deposit_amount: 4300000,
    electricity_cost: 3900,
    water_cost: 22000,
    internet_cost: 90000,
    service_fee: 70000,
    average_rating: 4.2,
    room_description: 'Phòng khép kín sạch đẹp, rất gần cổng chính bệnh viện Bạch Mai và cụm các trường đại học Bách-Kinh-Xây, nằm trong khu dân cư an ninh cao.',
  },
  {
    title: 'Studio nội thất xịn view sông Hàn',
    room_type: 'Căn hộ',
    detailed_address: '120 Bạch Đằng',
    ward_name: 'Hải Châu 1',
    district_name: 'Hải Châu',
    province_name: 'Đà Nẵng',
    formatted_address: '120 Bạch Đằng, Hải Châu 1, Hải Châu, Đà Nẵng, Việt Nam',
    latitude: 16.068248,
    longitude: 108.224121,
    max_capacity: 2,
    monthly_rent: 6500000,
    deposit_amount: 6500000,
    electricity_cost: 4100,
    water_cost: 24000,
    internet_cost: 120000,
    service_fee: 120000,
    average_rating: 4.8,
    room_description: 'Studio sở hữu view trực diện ngắm trọn sông Hàn thơ mộng, cách cầu Rồng vài bước chân, nội thất sang xịn mịn, ban công rộng, bếp nhỏ nhắn xinh xắn.',
  },
  {
    title: 'Phòng thông thoáng gần biển Mỹ Khê',
    room_type: 'Phòng trọ',
    detailed_address: '53 Nguyễn Văn Thoại',
    ward_name: 'Mỹ An',
    district_name: 'Ngũ Hành Sơn',
    province_name: 'Đà Nẵng',
    formatted_address: '53 Nguyễn Văn Thoại, Mỹ An, Ngũ Hành Sơn, Đà Nẵng, Việt Nam',
    latitude: 16.052269,
    longitude: 108.244603,
    max_capacity: 2,
    monthly_rent: 4800000,
    deposit_amount: 4800000,
    electricity_cost: 4000,
    water_cost: 23000,
    internet_cost: 100000,
    service_fee: 80000,
    average_rating: 4.5,
    room_description: 'Chỉ mất 5 phút đi bộ ra bãi biển Mỹ Khê sầm uất, phòng có sẵn máy lạnh đời mới, cửa sổ to, khu vực xung quanh ngập tràn quán ăn hải sản và tiện ích.',
  },
  {
    title: 'Căn hộ mini cao cấp Sơn Trà',
    room_type: 'Căn hộ',
    detailed_address: '18 Hồ Nghinh',
    ward_name: 'Phước Mỹ',
    district_name: 'Sơn Trà',
    province_name: 'Đà Nẵng',
    formatted_address: '18 Hồ Nghinh, Phước Mỹ, Sơn Trà, Đà Nẵng, Việt Nam',
    latitude: 16.069728,
    longitude: 108.243079,
    max_capacity: 2,
    monthly_rent: 5400000,
    deposit_amount: 5400000,
    electricity_cost: 4000,
    water_cost: 24000,
    internet_cost: 100000,
    service_fee: 90000,
    average_rating: 4.6,
    room_description: 'Căn hộ mini thiết kế ấm cúng, khoảng cách rất gần biển, trang bị khu bếp nấu ăn riêng biệt, khu vực giặt phơi chung rộng rãi và hệ thống camera an ninh tuyệt đối.',
  },
  {
    title: 'Phòng trọ sinh viên trung tâm Ninh Kiều',
    room_type: 'Phòng trọ',
    detailed_address: '32 Hai Bà Trưng',
    ward_name: 'Tân An',
    district_name: 'Ninh Kiều',
    province_name: 'Cần Thơ',
    formatted_address: '32 Hai Bà Trưng, Tân An, Ninh Kiều, Cần Thơ, Việt Nam',
    latitude: 10.034185,
    longitude: 105.788192,
    max_capacity: 2,
    monthly_rent: 3600000,
    deposit_amount: 3600000,
    electricity_cost: 3800,
    water_cost: 20000,
    internet_cost: 80000,
    service_fee: 50000,
    average_rating: 4.3,
    room_description: 'Phòng trọ tọa lạc ngay cạnh bến Ninh Kiều nhộn nhịp, vị trí thuận tiện di chuyển mọi nơi, thiết kế có nhà vệ sinh riêng và bãi đậu xe có quản lý.',
  },
  {
    title: 'Studio siêu rẻ gần Đại học Cần Thơ',
    room_type: 'Căn hộ',
    detailed_address: '3/2 Đường 3 Tháng 2',
    ward_name: 'Xuân Khánh',
    district_name: 'Ninh Kiều',
    province_name: 'Cần Thơ',
    formatted_address: 'Đường 3 Tháng 2, Xuân Khánh, Ninh Kiều, Cần Thơ, Việt Nam',
    latitude: 10.030684,
    longitude: 105.770739,
    max_capacity: 2,
    monthly_rent: 4200000,
    deposit_amount: 4200000,
    electricity_cost: 3800,
    water_cost: 21000,
    internet_cost: 90000,
    service_fee: 60000,
    average_rating: 4.4,
    room_description: 'Studio cách Đại học Cần Thơ chỉ 1km, trang bị nội thất ở mức cơ bản nhưng mới mẻ, là lựa chọn cực kỳ thích hợp cho sinh viên và nhân viên văn phòng.',
  },
  {
    title: 'Phòng trọ lối đi riêng Cái Răng',
    room_type: 'Phòng trọ',
    detailed_address: '92 Nguyễn Văn Cừ',
    ward_name: 'An Khánh',
    district_name: 'Ninh Kiều',
    province_name: 'Cần Thơ',
    formatted_address: '92 Nguyễn Văn Cừ, An Khánh, Ninh Kiều, Cần Thơ, Việt Nam',
    latitude: 10.044128,
    longitude: 105.752609,
    max_capacity: 2,
    monthly_rent: 3300000,
    deposit_amount: 3300000,
    electricity_cost: 3700,
    water_cost: 20000,
    internet_cost: 80000,
    service_fee: 50000,
    average_rating: 4.1,
    room_description: 'Phòng có lối đi riêng tư, tích hợp bếp riêng sạch sẽ, nằm trong khu xóm đạo yên bình, gần kề siêu thị và trạm dừng tuyến xe buýt chính đi vào trung tâm.',
  },
  {
    title: 'Căn hộ 1PN ban công đón gió Trần Duy Hưng',
    room_type: 'Căn hộ',
    detailed_address: '119 Trần Duy Hưng',
    ward_name: 'Trung Hòa',
    district_name: 'Cầu Giấy',
    province_name: 'Hà Nội',
    formatted_address: '119 Trần Duy Hưng, Trung Hòa, Cầu Giấy, Hà Nội, Việt Nam',
    latitude: 21.007855,
    longitude: 105.794311,
    max_capacity: 3,
    monthly_rent: 8200000,
    deposit_amount: 8200000,
    electricity_cost: 4300,
    water_cost: 26000,
    internet_cost: 150000,
    service_fee: 180000,
    average_rating: 4.7,
    room_description: 'Căn hộ một phòng ngủ tuyệt đẹp sát siêu thị Big C Thăng Long, trang bị sofa êm ái, khu bếp hiện đại và có cả máy giặt riêng thuận tiện.',
  },
  {
    title: 'Phòng gác cao mới xây KCN Tân Bình',
    room_type: 'Phòng trọ',
    detailed_address: '15 Tây Thạnh',
    ward_name: 'Tây Thạnh',
    district_name: 'Tân Phú',
    province_name: 'Hồ Chí Minh',
    formatted_address: '15 Tây Thạnh, Tây Thạnh, Tân Phú, Hồ Chí Minh, Việt Nam',
    latitude: 10.809938,
    longitude: 106.623453,
    max_capacity: 2,
    monthly_rent: 3900000,
    deposit_amount: 3900000,
    electricity_cost: 3900,
    water_cost: 22000,
    internet_cost: 80000,
    service_fee: 60000,
    average_rating: 4.2,
    room_description: 'Phòng trọ xây dựng theo mẫu mới nhất với gác cực kỳ cao, sát KCN Tân Bình, ưu điểm giờ giấc hoàn toàn tự do, gắn sẵn máy lạnh và có chỗ bãi giữ xe ngay tại tầng trệt.',
  },
  // --- 10 NEW ROOMS (Nhà trọ, 2-3 triệu) ---
  {
    title: 'Phòng trọ giá rẻ sinh viên Làng Đại học',
    room_type: 'Phòng trọ',
    detailed_address: 'Khu phố 6',
    ward_name: 'Linh Trung',
    district_name: 'Thành phố Thủ Đức',
    province_name: 'Hồ Chí Minh',
    formatted_address: 'Khu phố 6, Linh Trung, Thành phố Thủ Đức, Hồ Chí Minh, Việt Nam',
    latitude: 10.870020,
    longitude: 106.802521,
    max_capacity: 2,
    monthly_rent: 2200000,
    deposit_amount: 2200000,
    electricity_cost: 3500,
    water_cost: 15000,
    internet_cost: 60000,
    service_fee: 40000,
    average_rating: 4.1,
    room_description: 'Phòng trọ giá cực sinh viên nằm ngay Làng Đại học Quốc Gia, an ninh tốt, giờ giấc tự do, điện nước tính theo giá nhà nước rất tiết kiệm.',
  },
  {
    title: 'Phòng trọ gác lửng Lê Trọng Tấn',
    room_type: 'Phòng trọ',
    detailed_address: '234 Lê Trọng Tấn',
    ward_name: 'Tây Thạnh',
    district_name: 'Tân Phú',
    province_name: 'Hồ Chí Minh',
    formatted_address: '234 Lê Trọng Tấn, Tây Thạnh, Tân Phú, Hồ Chí Minh, Việt Nam',
    latitude: 10.812239,
    longitude: 106.621008,
    max_capacity: 3,
    monthly_rent: 2800000,
    deposit_amount: 2800000,
    electricity_cost: 3800,
    water_cost: 20000,
    internet_cost: 70000,
    service_fee: 50000,
    average_rating: 4.2,
    room_description: 'Phòng có gác lửng sạch sẽ, diện tích rộng rãi phù hợp ở 2-3 người, hẻm xe máy rộng rãi, gần chợ và siêu thị Aeon Tân Phú.',
  },
  {
    title: 'Nhà trọ an ninh hẻm Phạm Văn Đồng',
    room_type: 'Phòng trọ',
    detailed_address: '124 Phạm Văn Đồng',
    ward_name: 'Phường 3',
    district_name: 'Gò Vấp',
    province_name: 'Hồ Chí Minh',
    formatted_address: '124 Phạm Văn Đồng, Phường 3, Gò Vấp, Hồ Chí Minh, Việt Nam',
    latitude: 10.815967,
    longitude: 106.680073,
    max_capacity: 2,
    monthly_rent: 3000000,
    deposit_amount: 3000000,
    electricity_cost: 3800,
    water_cost: 22000,
    internet_cost: 80000,
    service_fee: 60000,
    average_rating: 4.5,
    room_description: 'Nhà trọ khu vực an ninh hẻm lớn Phạm Văn Đồng, thuận tiện di chuyển ra sân bay hoặc trung tâm thành phố, có trang bị sẵn tủ quần áo.',
  },
  {
    title: 'Phòng trọ khép kín Cổ Nhuế',
    room_type: 'Phòng trọ',
    detailed_address: '56 Cổ Nhuế',
    ward_name: 'Cổ Nhuế 2',
    district_name: 'Bắc Từ Liêm',
    province_name: 'Hà Nội',
    formatted_address: '56 Cổ Nhuế, Cổ Nhuế 2, Bắc Từ Liêm, Hà Nội, Việt Nam',
    latitude: 21.054320,
    longitude: 105.776180,
    max_capacity: 2,
    monthly_rent: 2500000,
    deposit_amount: 2500000,
    electricity_cost: 3800,
    water_cost: 20000,
    internet_cost: 70000,
    service_fee: 50000,
    average_rating: 4.0,
    room_description: 'Phòng trọ khép kín sạch sẽ, nấu ăn trong phòng, gần Học viện Cảnh sát và Đại học Mỏ - Địa chất, khu dân cư thân thiện.',
  },
  {
    title: 'Phòng trọ giá bình dân Triều Khúc',
    room_type: 'Phòng trọ',
    detailed_address: '12 Ngõ 68 Triều Khúc',
    ward_name: 'Tân Triều',
    district_name: 'Thanh Trì',
    province_name: 'Hà Nội',
    formatted_address: '12 Ngõ 68 Triều Khúc, Tân Triều, Thanh Trì, Hà Nội, Việt Nam',
    latitude: 20.980645,
    longitude: 105.797205,
    max_capacity: 2,
    monthly_rent: 2400000,
    deposit_amount: 2400000,
    electricity_cost: 3500,
    water_cost: 18000,
    internet_cost: 60000,
    service_fee: 40000,
    average_rating: 4.3,
    room_description: 'Phòng trọ khu vực Triều Khúc, ngõ rộng dễ tìm, cực kỳ thuận tiện cho các bạn sinh viên Đại học Công nghệ Giao thông Vận tải.',
  },
  {
    title: 'Nhà trọ sạch đẹp Trương Định',
    room_type: 'Phòng trọ',
    detailed_address: 'Ngõ 104 Trương Định',
    ward_name: 'Trương Định',
    district_name: 'Hai Bà Trưng',
    province_name: 'Hà Nội',
    formatted_address: 'Ngõ 104 Trương Định, Trương Định, Hai Bà Trưng, Hà Nội, Việt Nam',
    latitude: 20.993410,
    longitude: 105.845681,
    max_capacity: 2,
    monthly_rent: 2900000,
    deposit_amount: 2900000,
    electricity_cost: 4000,
    water_cost: 22000,
    internet_cost: 80000,
    service_fee: 60000,
    average_rating: 4.4,
    room_description: 'Phòng nằm trong căn nhà nguyên căn, không gian chung sạch sẽ thoáng mát, khu vực an ninh tuyệt đối, gần bến xe Giáp Bát.',
  },
  {
    title: 'Phòng trọ Liên Chiểu gần ĐH Bách Khoa ĐN',
    room_type: 'Phòng trọ',
    detailed_address: '15 Tôn Đức Thắng',
    ward_name: 'Hòa Minh',
    district_name: 'Liên Chiểu',
    province_name: 'Đà Nẵng',
    formatted_address: '15 Tôn Đức Thắng, Hòa Minh, Liên Chiểu, Đà Nẵng, Việt Nam',
    latitude: 16.059296,
    longitude: 108.156524,
    max_capacity: 2,
    monthly_rent: 2000000,
    deposit_amount: 2000000,
    electricity_cost: 3500,
    water_cost: 15000,
    internet_cost: 60000,
    service_fee: 40000,
    average_rating: 4.2,
    room_description: 'Phòng trọ xây mới, rộng rãi, khu vực an ninh tốt ngay gần Đại học Bách Khoa và Sư Phạm Đà Nẵng, thích hợp ở dài lâu.',
  },
  {
    title: 'Nhà trọ bình dân Hải Châu',
    room_type: 'Phòng trọ',
    detailed_address: 'K20/5 Phan Châu Trinh',
    ward_name: 'Hải Châu 1',
    district_name: 'Hải Châu',
    province_name: 'Đà Nẵng',
    formatted_address: 'K20/5 Phan Châu Trinh, Hải Châu 1, Hải Châu, Đà Nẵng, Việt Nam',
    latitude: 16.067645,
    longitude: 108.221568,
    max_capacity: 2,
    monthly_rent: 2700000,
    deposit_amount: 2700000,
    electricity_cost: 3800,
    water_cost: 20000,
    internet_cost: 70000,
    service_fee: 50000,
    average_rating: 4.1,
    room_description: 'Nhà trọ ngay trung tâm quận Hải Châu, đi lại siêu tiện lợi, đầy đủ tiện ích xung quanh, chủ nhà thân thiện và hỗ trợ nhiệt tình.',
  },
  {
    title: 'Phòng trọ khu vực Cái Răng giá rẻ',
    room_type: 'Phòng trọ',
    detailed_address: 'Khu dân cư 586',
    ward_name: 'Phú Thứ',
    district_name: 'Cái Răng',
    province_name: 'Cần Thơ',
    formatted_address: 'Khu dân cư 586, Phú Thứ, Cái Răng, Cần Thơ, Việt Nam',
    latitude: 10.003932,
    longitude: 105.783637,
    max_capacity: 2,
    monthly_rent: 2100000,
    deposit_amount: 2100000,
    electricity_cost: 3500,
    water_cost: 15000,
    internet_cost: 50000,
    service_fee: 30000,
    average_rating: 4.0,
    room_description: 'Phòng trọ giá mềm nằm trong khu dân cư yên tĩnh, an ninh đảm bảo, đường xá thoáng mát rộng rãi thuận tiện đi chuyển.',
  },
  {
    title: 'Nhà trọ sinh viên Mậu Thân',
    room_type: 'Phòng trọ',
    detailed_address: 'Hẻm 51 Mậu Thân',
    ward_name: 'Xuân Khánh',
    district_name: 'Ninh Kiều',
    province_name: 'Cần Thơ',
    formatted_address: 'Hẻm 51 Mậu Thân, Xuân Khánh, Ninh Kiều, Cần Thơ, Việt Nam',
    latitude: 10.035768,
    longitude: 105.772591,
    max_capacity: 2,
    monthly_rent: 2300000,
    deposit_amount: 2300000,
    electricity_cost: 3800,
    water_cost: 18000,
    internet_cost: 60000,
    service_fee: 40000,
    average_rating: 4.3,
    room_description: 'Hẻm ăn uống nổi tiếng Mậu Thân, rất đông vui nhộn nhịp, chỉ mất vài phút ra đến Đại học Cần Thơ, lý tưởng cho sinh viên ở trọ.',
  }
];

exports.seed = async function (knex) {
  // Clear existing to prevent constraint violations
  await knex('room_images').del();
  await knex('rooms').del();

  const roomRows = rooms.map((room, index) => ({
    room_id: `d0000000-0000-0000-0000-${String(index + 1).padStart(12, '0')}`,
    landlord_id: index % 2 === 0 ? 'c0000000-0000-0000-0000-000000000002' : 'c0000000-0000-0000-0000-000000000003',
    title: room.title,
    room_type: room.room_type,
    detailed_address: room.detailed_address,
    province_name: room.province_name,
    district_name: room.district_name,
    ward_name: room.ward_name,
    formatted_address: room.formatted_address,
    place_id: `seed-place-${String(index + 1).padStart(2, '0')}`,
    max_capacity: room.max_capacity,
    monthly_rent: room.monthly_rent,
    deposit_amount: room.deposit_amount,
    electricity_cost: room.electricity_cost,
    water_cost: room.water_cost,
    internet_cost: room.internet_cost,
    service_fee: room.service_fee,
    status: 'AVAILABLE',
    average_rating: room.average_rating,
    room_description: room.room_description,
    longitude: room.longitude,
    latitude: room.latitude,
  }));

  await knex('rooms').insert(roomRows);

  const imageRows = rooms.flatMap((_, roomIndex) => {
    // each room has 3 images
    return [1, 2, 3].map((imageIndex) => ({
      room_id: `d0000000-0000-0000-0000-${String(roomIndex + 1).padStart(12, '0')}`,
      sequence_number: imageIndex,
      image_url: imageUrl(roomIndex + 1, imageIndex),
      is_cover: imageIndex === 1,
    }));
  });

  await knex('room_images').insert(imageRows);
};
